;;;-*- mode: emacs-lisp -*-
(de NCONC (X Y)
    (prog (M)
	  (go (cond ((null X) 'RETY) (t 'CONT)))
CONT (a M X)
A1   (go (cond ((null (cdr M)) 'A2) (t 'MORE)))
MORE (a M (cdr M))
     (go 'A1)
A2   (rplacd M Y) 
RETN (return X)
RETY (return Y)))
